### ISSUE TITLE
I don't think we can say 'didn't see none'. Any instead of none, I suppose.

### ISSUE THREAD

**Issue by KatyaGotskina** [siriusdevs/rpm-hws_7-1_2023#10]
well, i asked for linters and tests.. didnt see none

_Originally posted by @siriusdevs in https://github.com/siriusdevs/rpm-hws_7-1_2023/pull/5#discussion_r1145281167_

**Comment by siriusdevs** [comment]
[Page](https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/didn%27t+see+none) with examples of usage

There is a Cambridge Dictionary [page](https://dictionary.cambridge.org/grammar/british-grammar/no-none-and-none-of), it claims:
>None is the pronoun form of no. None means ‘not one’ or ‘not any’. We use it as a pronoun to replace countable and uncountable nouns. We use it as subject or object:
> Slorne stared … and seemed to try to find some strength which would let her speak. But none came. (No strength came.)

**Comment by siriusdevs** [comment]
I don't say that I am a 100% right. Is that a mistake, though? I am not teaching English :smile_cat:

**Comment by siriusdevs** [comment]
Well, I actually was wrong.
Маргарита Сергеевна said:

> Quantitive noun “none” is used in affirmatives sentences:
> For instance: 
> •I see none problems 
> •He asked me to check in a spam box. But there were none.
> 
> Pronoun “any” is used in negative sentences. 
> As in:
>  • I didn’t see any problems.
>  • He asked me to check the spam email. But there weren’t any.
